# Generated by Django 5.0.2 on 2024-04-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('logement', 'Logement'), ('stage', 'Stage')], default='logement', max_length=20),
        ),
    ]
