# Generated by Django 5.0.2 on 2024-04-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transport_images'),
        ),
    ]
