# Generated by Django 5.0.3 on 2024-04-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transport_moyen_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='type',
        ),
    ]
