# Generated by Django 5.0.3 on 2024-04-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_stage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('ouvrier', 'ouvrier'), ('technicien', 'technicien'), ('PFE', 'PFE')], default='ouvrier', max_length=50),
        ),
    ]
