# Generated by Django 5.0.3 on 2024-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='nb_interessés',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
