# Generated by Django 5.0.3 on 2024-04-28 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_evenement_nb_interessés'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='interesses',
            field=models.ManyToManyField(blank=True, related_name='evenements_interesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
