# Generated by Django 5.0.3 on 2024-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transport_reserve_transport_reserve_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='reserve',
        ),
        migrations.AddField(
            model_name='transport',
            name='nbr_reservations',
            field=models.IntegerField(default=0),
        ),
    ]
