# Generated by Django 5.0.3 on 2024-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_transport_reserve_transport_nbr_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='est_reserve',
            field=models.BooleanField(default=False),
        ),
    ]
