# Generated by Django 5.0.3 on 2024-04-28 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transport_est_reserve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='interesses',
            field=models.ManyToManyField(related_name='interets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='nombre_interets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
