# Generated by Django 5.0.3 on 2024-04-28 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_stage_interesses_stage_nombre_interets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='interesses',
            field=models.ManyToManyField(blank=True, related_name='stages_interesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
