# Generated by Django 5.0.3 on 2024-05-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contactmessage_notification_post_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
