# Generated by Django 5.0.3 on 2024-05-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_smallbusiness_businesspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
