# Generated by Django 5.0.3 on 2024-05-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_smallbusiness_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallbusiness',
            name='user',
        ),
        migrations.AddField(
            model_name='smallbusiness',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
