# Generated by Django 5.0.3 on 2024-05-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comts',
        ),
    ]
