# Generated by Django 5.0.3 on 2024-05-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_comments_comts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comnts', to='core.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Comts',
        ),
    ]
