# Generated by Django 5.0.3 on 2024-05-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
